version: '3.7'
services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: plezanjenet
      POSTGRES_USER: plezanjenet
      POSTGRES_PASSWORD: plezanjenet
    ports:
      - "5432:5432"
