import {MigrationInterface, QueryRunner} from "typeorm";

export class initialize1638625192658 implements MigrationInterface {
    name = 'initialize1638625192658'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "role" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "role" character varying NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "legacy" character varying, "userId" uuid NOT NULL, CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "club" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "legacy" character varying, CONSTRAINT "UQ_79098e276529e2f823ab6379e8f" UNIQUE ("name"), CONSTRAINT "UQ_f8387c04fc077b826b2ad11825e" UNIQUE ("slug"), CONSTRAINT "PK_79282481e036a6e0b180afa38aa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "club_member" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "admin" boolean NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "legacy" character varying, "userId" uuid NOT NULL, "clubId" uuid NOT NULL, CONSTRAINT "UQ_2c43d1e91c77185c7970b9ca11f" UNIQUE ("userId", "clubId"), CONSTRAINT "PK_d6cfd9e17ca944f4eeedf5ef908" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "firstname" character varying NOT NULL, "lastname" character varying NOT NULL, "www" character varying, "gender" character varying, "picture" character varying, "password" character varying, "passwordToken" character varying, "confirmationToken" character varying, "isActive" boolean NOT NULL DEFAULT false, "isPublic" boolean NOT NULL DEFAULT false, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "legacy" character varying, CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "book" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "author" character varying, "publisher" character varying, "year" integer, "url" character varying, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "legacy" character varying, CONSTRAINT "PK_a3afef72ec8f80e6e5c310b28a4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "peak" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "height" integer, "lat" double precision, "lon" double precision, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "legacy" character varying, "areaId" uuid, "countryId" uuid, CONSTRAINT "PK_638f426f513cba624c3011aa0e4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ice_fall" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "difficulty" character varying, "height" integer, "access" text, "description" text, "position" integer NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "legacy" character varying, "countryId" uuid, "areaId" uuid, CONSTRAINT "PK_ab333c7ed71b47b9d8d4295ead5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."comment_type_enum" AS ENUM('warning', 'condition', 'description', 'comment')`);
        await queryRunner.query(`CREATE TYPE "public"."comment_status_enum" AS ENUM('active', 'archived')`);
        await queryRunner.query(`CREATE TABLE "comment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."comment_type_enum" NOT NULL DEFAULT 'comment', "userId" uuid, "content" text, "status" "public"."comment_status_enum" NOT NULL DEFAULT 'active', "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "legacy" character varying, "routeId" uuid, "cragId" uuid, "iceFallId" uuid, "peakId" uuid, CONSTRAINT "PK_0b0e4bbc8415ec426f87f3a88e2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."image_type_enum" AS ENUM('photo', 'sketch', 'map', 'profile')`);
        await queryRunner.query(`CREATE TABLE "image" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."image_type_enum" NOT NULL DEFAULT 'photo', "title" character varying, "description" character varying, "path" character varying NOT NULL, "extension" character varying NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "legacy" character varying, "userId" uuid, "areaId" uuid, "cragId" uuid, "routeId" uuid, "iceFallId" uuid, "commentId" uuid, "peakId" uuid, CONSTRAINT "PK_d6db1ab4ee9ad9dbe86c64e4cc3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "area" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying COLLATE "utf8_slovenian_ci" NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "legacy" character varying, "nrCrags" integer NOT NULL DEFAULT '0', "countryId" uuid, CONSTRAINT "PK_39d5e4de490139d6535d75f42ff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "country" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "legacy" character varying, "nrCrags" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_8ff4c23dc9a3f3856555bd86186" UNIQUE ("code"), CONSTRAINT "UQ_4cd2b9410fe9cb70466134c2f9a" UNIQUE ("slug"), CONSTRAINT "PK_bf6e37c231c4f4ea56dcd887269" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."activity_type_enum" AS ENUM('crag', 'climbingGym', 'trainingGym', 'peak', 'iceFall', 'other')`);
        await queryRunner.query(`CREATE TABLE "activity" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."activity_type_enum" NOT NULL DEFAULT 'other', "name" character varying, "date" TIMESTAMP, "duration" integer, "notes" character varying, "partners" character varying, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "legacy" character varying, "cragId" uuid, "iceFallId" uuid, "peakId" uuid, "userId" uuid NOT NULL, CONSTRAINT "PK_24625a1d6b1b089c8ae206fe467" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."crag_status_enum" AS ENUM('public', 'hidden', 'admin', 'archive', 'proposal', 'user')`);
        await queryRunner.query(`CREATE TABLE "crag" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "status" "public"."crag_status_enum" NOT NULL DEFAULT 'public', "lat" double precision, "lon" double precision, "orientation" character varying, "access" text, "description" text, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "legacy" character varying, "nrRoutes" integer NOT NULL DEFAULT '0', "minGrade" character varying, "maxGrade" character varying, "areaId" uuid, "peakId" uuid, "countryId" uuid, CONSTRAINT "UQ_bb9c118ecf33f4a27cfa0a74b29" UNIQUE ("slug"), CONSTRAINT "PK_4c045dd4425e6545993cfa6dc68" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."sector_status_enum" AS ENUM('public', 'hidden', 'admin', 'archive', 'proposal', 'user')`);
        await queryRunner.query(`CREATE TABLE "sector" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying, "label" character varying, "position" integer NOT NULL, "status" "public"."sector_status_enum" NOT NULL DEFAULT 'public', "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "legacy" character varying, "cragId" uuid NOT NULL, CONSTRAINT "PK_668b2ea8a2f534425407732f3ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "grade" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "grade" double precision NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "legacy" character varying, "isBase" boolean, "userId" uuid, "routeId" uuid, CONSTRAINT "PK_58c2176c3ae96bf57daebdbcb5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pitch" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "routeId" uuid NOT NULL, "number" integer NOT NULL, "difficulty" character varying, "height" integer, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "legacy" character varying, CONSTRAINT "PK_8174512e26c5adb6879b299f3e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rating" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "stars" integer NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "routeId" uuid, CONSTRAINT "PK_ecda8ad32645327e4765b43649e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."route_type_enum" AS ENUM('sport', 'multipitch', 'boulder', 'alpine', 'indoor', 'combined')`);
        await queryRunner.query(`CREATE TYPE "public"."route_status_enum" AS ENUM('public', 'hidden', 'admin', 'archive', 'proposal', 'user')`);
        await queryRunner.query(`CREATE TABLE "route" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."route_type_enum" NOT NULL DEFAULT 'sport', "name" character varying NOT NULL, "difficulty" character varying, "grade" double precision, "length" integer, "author" character varying, "position" integer NOT NULL, "status" "public"."route_status_enum" NOT NULL DEFAULT 'public', "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "legacy" character varying, "sectorId" uuid NOT NULL, "cragId" uuid, CONSTRAINT "PK_08affcd076e46415e5821acf52d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."activity_route_ascenttype_enum" AS ENUM('onsight', 'flash', 'redpoint', 'repeat', 'allfree', 'aid', 'attempt', 't_onsight', 't_flash', 't_redpoint', 't_repeat', 't_allfree', 't_aid', 't_attempt', 'tick')`);
        await queryRunner.query(`CREATE TYPE "public"."activity_route_publish_enum" AS ENUM('public', 'club', 'log', 'private')`);
        await queryRunner.query(`CREATE TABLE "activity_route" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "legacy" character varying, "ascentType" "public"."activity_route_ascenttype_enum" NOT NULL DEFAULT 'redpoint', "name" character varying, "difficulty" character varying, "grade" double precision, "publish" "public"."activity_route_publish_enum" NOT NULL DEFAULT 'private', "date" TIMESTAMP, "notes" character varying, "partner" character varying, "position" integer, "stars" integer, "activityId" uuid, "routeId" uuid, "pitchId" uuid, "userId" uuid NOT NULL, CONSTRAINT "PK_6364ca0b696125ff098b9629ba5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "handler" character varying, "input" json, "user" character varying, "action" character varying, "entity" character varying, "entityId" character varying, "dataBefore" json, "dataAfter" json, "created" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1d3d120ddaf7bc9b1ed68ed463a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "peak_books_book" ("peakId" uuid NOT NULL, "bookId" uuid NOT NULL, CONSTRAINT "PK_3860b786748587ce14cf7a3d6d0" PRIMARY KEY ("peakId", "bookId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2e7b12570bae2daeee0b7362e7" ON "peak_books_book" ("peakId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6eb00ea7063b28380c1a50afca" ON "peak_books_book" ("bookId") `);
        await queryRunner.query(`CREATE TABLE "crag_books_book" ("cragId" uuid NOT NULL, "bookId" uuid NOT NULL, CONSTRAINT "PK_9f10cbc3495027511ce4e442e5c" PRIMARY KEY ("cragId", "bookId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e94feb279ddaacbf626e5c9911" ON "crag_books_book" ("cragId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0e2d561f05690e75a87568e21c" ON "crag_books_book" ("bookId") `);
        await queryRunner.query(`ALTER TABLE "role" ADD CONSTRAINT "FK_3e02d32dd4707c91433de0390ea" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "club_member" ADD CONSTRAINT "FK_ba6f4421c170b49f0ca6ea52720" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "club_member" ADD CONSTRAINT "FK_1047687a2fa4d8aa55ce9ff46ad" FOREIGN KEY ("clubId") REFERENCES "club"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "peak" ADD CONSTRAINT "FK_718d08509a4895f37a2a70b465d" FOREIGN KEY ("areaId") REFERENCES "area"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "peak" ADD CONSTRAINT "FK_53a36c2642b09e474534a5c13d3" FOREIGN KEY ("countryId") REFERENCES "country"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ice_fall" ADD CONSTRAINT "FK_6a195788507dd2367e76bfdadf0" FOREIGN KEY ("countryId") REFERENCES "country"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ice_fall" ADD CONSTRAINT "FK_be4921538405d090ca0f909b8d6" FOREIGN KEY ("areaId") REFERENCES "area"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment" ADD CONSTRAINT "FK_c0354a9a009d3bb45a08655ce3b" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment" ADD CONSTRAINT "FK_a96b20ea74a1f9fd048093143d9" FOREIGN KEY ("cragId") REFERENCES "crag"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment" ADD CONSTRAINT "FK_a05ad82a595340696de65f7ec38" FOREIGN KEY ("routeId") REFERENCES "route"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment" ADD CONSTRAINT "FK_01c5c187a3658e66c06e7afb897" FOREIGN KEY ("iceFallId") REFERENCES "ice_fall"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment" ADD CONSTRAINT "FK_c66cb2dfccd160ea0bff6bab318" FOREIGN KEY ("peakId") REFERENCES "peak"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "image" ADD CONSTRAINT "FK_dc40417dfa0c7fbd70b8eb880cc" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "image" ADD CONSTRAINT "FK_0613e7f6523de4f2cbb9201545c" FOREIGN KEY ("areaId") REFERENCES "area"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "image" ADD CONSTRAINT "FK_ab658297e41b589fe04fa13c14f" FOREIGN KEY ("cragId") REFERENCES "crag"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "image" ADD CONSTRAINT "FK_6167c683c3c25c2690a4fb82f24" FOREIGN KEY ("routeId") REFERENCES "route"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "image" ADD CONSTRAINT "FK_aa7ec9ab343e6abf53aaa29d00c" FOREIGN KEY ("iceFallId") REFERENCES "ice_fall"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "image" ADD CONSTRAINT "FK_09448fcefb6d065d9ad09d7a22e" FOREIGN KEY ("commentId") REFERENCES "comment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "image" ADD CONSTRAINT "FK_67ab23d4e8d3e74fe6c4ef3c936" FOREIGN KEY ("peakId") REFERENCES "peak"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "area" ADD CONSTRAINT "FK_cae1d5b69fc10cb70c83f348702" FOREIGN KEY ("countryId") REFERENCES "country"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity" ADD CONSTRAINT "FK_626d254ca76bdbb0be1aef6b7c9" FOREIGN KEY ("cragId") REFERENCES "crag"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity" ADD CONSTRAINT "FK_3b16ef8dad0342ea8569caf0741" FOREIGN KEY ("iceFallId") REFERENCES "ice_fall"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity" ADD CONSTRAINT "FK_ddf8003d229c023dd29641c3cb0" FOREIGN KEY ("peakId") REFERENCES "peak"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity" ADD CONSTRAINT "FK_3571467bcbe021f66e2bdce96ea" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "crag" ADD CONSTRAINT "FK_eadbb840424bf1e9b6b4cc483d9" FOREIGN KEY ("areaId") REFERENCES "area"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "crag" ADD CONSTRAINT "FK_57c5b20f5db1b23f708d81dadad" FOREIGN KEY ("peakId") REFERENCES "peak"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "crag" ADD CONSTRAINT "FK_917e2c3829ffac20bbb3b93543b" FOREIGN KEY ("countryId") REFERENCES "country"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sector" ADD CONSTRAINT "FK_3f7e3dea0cbd160c8bbc86ec0e0" FOREIGN KEY ("cragId") REFERENCES "crag"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grade" ADD CONSTRAINT "FK_8bb7e985f57c47948850542f9d6" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grade" ADD CONSTRAINT "FK_98de1cfd884855b655de18974ea" FOREIGN KEY ("routeId") REFERENCES "route"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pitch" ADD CONSTRAINT "FK_8e284cf2399299bb4a94aa9b7ba" FOREIGN KEY ("routeId") REFERENCES "route"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rating" ADD CONSTRAINT "FK_a6c53dfc89ba3188b389ef29a62" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rating" ADD CONSTRAINT "FK_d27aa63516652f5e49b6379e065" FOREIGN KEY ("routeId") REFERENCES "route"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "route" ADD CONSTRAINT "FK_6ee50bb725ec5b94b0a2f988331" FOREIGN KEY ("cragId") REFERENCES "crag"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "route" ADD CONSTRAINT "FK_6429a184ba403a6d346f59436fa" FOREIGN KEY ("sectorId") REFERENCES "sector"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_route" ADD CONSTRAINT "FK_e2996eef518bf566d4a92305101" FOREIGN KEY ("activityId") REFERENCES "activity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_route" ADD CONSTRAINT "FK_ebb17ba34f1d7783c1c146d062e" FOREIGN KEY ("routeId") REFERENCES "route"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_route" ADD CONSTRAINT "FK_8fcfc26571a56a81b37f74c6d28" FOREIGN KEY ("pitchId") REFERENCES "pitch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_route" ADD CONSTRAINT "FK_5d0f4cc17e126ad509bcb6b81f7" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "peak_books_book" ADD CONSTRAINT "FK_2e7b12570bae2daeee0b7362e78" FOREIGN KEY ("peakId") REFERENCES "peak"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "peak_books_book" ADD CONSTRAINT "FK_6eb00ea7063b28380c1a50afca8" FOREIGN KEY ("bookId") REFERENCES "book"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "crag_books_book" ADD CONSTRAINT "FK_e94feb279ddaacbf626e5c9911e" FOREIGN KEY ("cragId") REFERENCES "crag"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "crag_books_book" ADD CONSTRAINT "FK_0e2d561f05690e75a87568e21cb" FOREIGN KEY ("bookId") REFERENCES "book"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "crag_books_book" DROP CONSTRAINT "FK_0e2d561f05690e75a87568e21cb"`);
        await queryRunner.query(`ALTER TABLE "crag_books_book" DROP CONSTRAINT "FK_e94feb279ddaacbf626e5c9911e"`);
        await queryRunner.query(`ALTER TABLE "peak_books_book" DROP CONSTRAINT "FK_6eb00ea7063b28380c1a50afca8"`);
        await queryRunner.query(`ALTER TABLE "peak_books_book" DROP CONSTRAINT "FK_2e7b12570bae2daeee0b7362e78"`);
        await queryRunner.query(`ALTER TABLE "activity_route" DROP CONSTRAINT "FK_5d0f4cc17e126ad509bcb6b81f7"`);
        await queryRunner.query(`ALTER TABLE "activity_route" DROP CONSTRAINT "FK_8fcfc26571a56a81b37f74c6d28"`);
        await queryRunner.query(`ALTER TABLE "activity_route" DROP CONSTRAINT "FK_ebb17ba34f1d7783c1c146d062e"`);
        await queryRunner.query(`ALTER TABLE "activity_route" DROP CONSTRAINT "FK_e2996eef518bf566d4a92305101"`);
        await queryRunner.query(`ALTER TABLE "route" DROP CONSTRAINT "FK_6429a184ba403a6d346f59436fa"`);
        await queryRunner.query(`ALTER TABLE "route" DROP CONSTRAINT "FK_6ee50bb725ec5b94b0a2f988331"`);
        await queryRunner.query(`ALTER TABLE "rating" DROP CONSTRAINT "FK_d27aa63516652f5e49b6379e065"`);
        await queryRunner.query(`ALTER TABLE "rating" DROP CONSTRAINT "FK_a6c53dfc89ba3188b389ef29a62"`);
        await queryRunner.query(`ALTER TABLE "pitch" DROP CONSTRAINT "FK_8e284cf2399299bb4a94aa9b7ba"`);
        await queryRunner.query(`ALTER TABLE "grade" DROP CONSTRAINT "FK_98de1cfd884855b655de18974ea"`);
        await queryRunner.query(`ALTER TABLE "grade" DROP CONSTRAINT "FK_8bb7e985f57c47948850542f9d6"`);
        await queryRunner.query(`ALTER TABLE "sector" DROP CONSTRAINT "FK_3f7e3dea0cbd160c8bbc86ec0e0"`);
        await queryRunner.query(`ALTER TABLE "crag" DROP CONSTRAINT "FK_917e2c3829ffac20bbb3b93543b"`);
        await queryRunner.query(`ALTER TABLE "crag" DROP CONSTRAINT "FK_57c5b20f5db1b23f708d81dadad"`);
        await queryRunner.query(`ALTER TABLE "crag" DROP CONSTRAINT "FK_eadbb840424bf1e9b6b4cc483d9"`);
        await queryRunner.query(`ALTER TABLE "activity" DROP CONSTRAINT "FK_3571467bcbe021f66e2bdce96ea"`);
        await queryRunner.query(`ALTER TABLE "activity" DROP CONSTRAINT "FK_ddf8003d229c023dd29641c3cb0"`);
        await queryRunner.query(`ALTER TABLE "activity" DROP CONSTRAINT "FK_3b16ef8dad0342ea8569caf0741"`);
        await queryRunner.query(`ALTER TABLE "activity" DROP CONSTRAINT "FK_626d254ca76bdbb0be1aef6b7c9"`);
        await queryRunner.query(`ALTER TABLE "area" DROP CONSTRAINT "FK_cae1d5b69fc10cb70c83f348702"`);
        await queryRunner.query(`ALTER TABLE "image" DROP CONSTRAINT "FK_67ab23d4e8d3e74fe6c4ef3c936"`);
        await queryRunner.query(`ALTER TABLE "image" DROP CONSTRAINT "FK_09448fcefb6d065d9ad09d7a22e"`);
        await queryRunner.query(`ALTER TABLE "image" DROP CONSTRAINT "FK_aa7ec9ab343e6abf53aaa29d00c"`);
        await queryRunner.query(`ALTER TABLE "image" DROP CONSTRAINT "FK_6167c683c3c25c2690a4fb82f24"`);
        await queryRunner.query(`ALTER TABLE "image" DROP CONSTRAINT "FK_ab658297e41b589fe04fa13c14f"`);
        await queryRunner.query(`ALTER TABLE "image" DROP CONSTRAINT "FK_0613e7f6523de4f2cbb9201545c"`);
        await queryRunner.query(`ALTER TABLE "image" DROP CONSTRAINT "FK_dc40417dfa0c7fbd70b8eb880cc"`);
        await queryRunner.query(`ALTER TABLE "comment" DROP CONSTRAINT "FK_c66cb2dfccd160ea0bff6bab318"`);
        await queryRunner.query(`ALTER TABLE "comment" DROP CONSTRAINT "FK_01c5c187a3658e66c06e7afb897"`);
        await queryRunner.query(`ALTER TABLE "comment" DROP CONSTRAINT "FK_a05ad82a595340696de65f7ec38"`);
        await queryRunner.query(`ALTER TABLE "comment" DROP CONSTRAINT "FK_a96b20ea74a1f9fd048093143d9"`);
        await queryRunner.query(`ALTER TABLE "comment" DROP CONSTRAINT "FK_c0354a9a009d3bb45a08655ce3b"`);
        await queryRunner.query(`ALTER TABLE "ice_fall" DROP CONSTRAINT "FK_be4921538405d090ca0f909b8d6"`);
        await queryRunner.query(`ALTER TABLE "ice_fall" DROP CONSTRAINT "FK_6a195788507dd2367e76bfdadf0"`);
        await queryRunner.query(`ALTER TABLE "peak" DROP CONSTRAINT "FK_53a36c2642b09e474534a5c13d3"`);
        await queryRunner.query(`ALTER TABLE "peak" DROP CONSTRAINT "FK_718d08509a4895f37a2a70b465d"`);
        await queryRunner.query(`ALTER TABLE "club_member" DROP CONSTRAINT "FK_1047687a2fa4d8aa55ce9ff46ad"`);
        await queryRunner.query(`ALTER TABLE "club_member" DROP CONSTRAINT "FK_ba6f4421c170b49f0ca6ea52720"`);
        await queryRunner.query(`ALTER TABLE "role" DROP CONSTRAINT "FK_3e02d32dd4707c91433de0390ea"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0e2d561f05690e75a87568e21c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e94feb279ddaacbf626e5c9911"`);
        await queryRunner.query(`DROP TABLE "crag_books_book"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6eb00ea7063b28380c1a50afca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2e7b12570bae2daeee0b7362e7"`);
        await queryRunner.query(`DROP TABLE "peak_books_book"`);
        await queryRunner.query(`DROP TABLE "audit"`);
        await queryRunner.query(`DROP TABLE "activity_route"`);
        await queryRunner.query(`DROP TYPE "public"."activity_route_publish_enum"`);
        await queryRunner.query(`DROP TYPE "public"."activity_route_ascenttype_enum"`);
        await queryRunner.query(`DROP TABLE "route"`);
        await queryRunner.query(`DROP TYPE "public"."route_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."route_type_enum"`);
        await queryRunner.query(`DROP TABLE "rating"`);
        await queryRunner.query(`DROP TABLE "pitch"`);
        await queryRunner.query(`DROP TABLE "grade"`);
        await queryRunner.query(`DROP TABLE "sector"`);
        await queryRunner.query(`DROP TYPE "public"."sector_status_enum"`);
        await queryRunner.query(`DROP TABLE "crag"`);
        await queryRunner.query(`DROP TYPE "public"."crag_status_enum"`);
        await queryRunner.query(`DROP TABLE "activity"`);
        await queryRunner.query(`DROP TYPE "public"."activity_type_enum"`);
        await queryRunner.query(`DROP TABLE "country"`);
        await queryRunner.query(`DROP TABLE "area"`);
        await queryRunner.query(`DROP TABLE "image"`);
        await queryRunner.query(`DROP TYPE "public"."image_type_enum"`);
        await queryRunner.query(`DROP TABLE "comment"`);
        await queryRunner.query(`DROP TYPE "public"."comment_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."comment_type_enum"`);
        await queryRunner.query(`DROP TABLE "ice_fall"`);
        await queryRunner.query(`DROP TABLE "peak"`);
        await queryRunner.query(`DROP TABLE "book"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "club_member"`);
        await queryRunner.query(`DROP TABLE "club"`);
        await queryRunner.query(`DROP TABLE "role"`);
    }

}
